### ISSUE TITLE
fix: Sourcemap missing?

### ISSUE THREAD

**Issue by nathanchase** [nuxt-modules/fontaine#136]
### 🐛 The bug

I'm seeing an error in the console when running `pnpm dev`:

> `Sourcemap for "virtual:nuxt:/home/myapp/.nuxt/font-override-inlining-plugin.server.ts" points to missing source files`

### 🛠️ To reproduce

https://stackblitz.com/edit/github-mqggve?file=package.json

### 🌈 Expected behaviour

Correct use of source maps?

**Comment by danielroe** [comment]
This should be resolved in 0.2.4. Let me know if not, and I'll reopen.

**Comment by nathanchase** [comment]
Yeah, still seeing "Sourcemap for "virtual:nuxt:/home/app/.nuxt/font-override-inlining-plugin.server.ts" points to missing source files" in 0.2.4. Visible in console at https://stackblitz.com/edit/github-mqggve?file=package.json

**Comment by danielroe** [comment]
It seems to be using 0.2.3.

![CleanShot 2023-01-06 at 16.51.14.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_01_06_at_16_51_14_1fcdbede5c.png)

**Comment by nathanchase** [comment]
Here's with 0.2.4 explicitly chosen: https://stackblitz.com/edit/github-mqggve-ppugwt?file=package-lock.json

**Comment by kaname-png** [comment]
Same problem here.
![image](https://user-images.githubusercontent.com/56084970/212207250-78f2b454-a0b5-4cdf-a43b-bbf3e3be147f.png)

nuxt: v3.0.0
fontaine: v0.2.4

**Comment by oneart-dev** [comment]
Nuxt v3.1.1
Fontaine v0.2.4

Same

**Comment by Bitcreep** [comment]
> Same problem here. ![image](https://user-images.githubusercontent.com/56084970/212207250-78f2b454-a0b5-4cdf-a43b-bbf3e3be147f.png)
> 
> nuxt: v3.0.0 fontaine: v0.2.4

same with Nuxt 3.2.0 , fontaine 0.2.4

**Comment by TutorFx** [comment]
same with "nuxt": "^3.1.0", "@nuxtjs/fontaine": "^0.2.4"

**Comment by danielroe** [comment]
This is no longer replicable for me on the latest fontaine: https://stackblitz.com/edit/github-mqggve-ppugwt?file=package.json.

Let me know if not and I'll happily reopen.
